#!/usr/bin/env python3
# Copyright 2025 Wayson
# SPDX-License-Identifier: MIT
# License text: https://opensource.org/licenses/MIT

# TODO H wayson 2025-10-13: string function study
# capitalize()
# center(width, fillchar)
# count(str, beg= 0,end=len(string))
# bytes.decode(encoding="utf-8", errors="strict")
# encode(encoding='UTF-8',errors='strict')
# endswith(suffix, beg=0, end=len(string))
# expandtabs(tabsize=8)
# find(str, beg=0, end=len(string))
# index(str, beg=0, end=len(string))
# isalnum()
# isalpha()
# isdigit()
# islower()
# isnumeric()
# isspace()
# istitle()
# isupper()
# join(seq)
# len(string)
# ljust(width[, fillchar])
# lower()
# lstrip()
# maketrans()
# max(str)
# min(str)
# replace(old, new [, max])
# rfind(str, beg=0,end=len(string))
# rindex( str, beg=0, end=len(string))
# rjust(width,[, fillchar])
# rstrip()
# split(str="", num=string.count(str))
# splitlines([keepends])
# startswith(substr, beg=0,end=len(string))
# strip([chars])
# swapcase()
# title()
# translate(table, deletechars="")
# upper()
# zfill (width)
# isdecimal()